# Generated by Django 3.0.5 on 2020-05-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tax_substitution', models.CharField(max_length=50)),
                ('cst_nfe', models.CharField(choices=[(0, 'Tributada integralmente'), (10, 'Tributada e com cobrança do ICMS por substituição tributária'), (20, 'Com redução da BC'), (30, 'Isenta / não tributada e com cobrança do ICMS por substituição tributária'), (40, 'Isenta'), (41, 'Não tributada'), (50, 'Com suspensão'), (51, 'Com diferimento'), (60, 'ICMS cobrado anteriormente por substituição tributária'), (70, 'Com redução da BC e cobrança do ICMS por substituição tributária'), (90, 'Outras')], default=0, max_length=2)),
                ('ncm_nfe', models.IntegerField()),
                ('origin', models.CharField(choices=[('NAC', 'Nacional'), ('IMP', 'Importado')], default='NAC', max_length=3)),
                ('bar_code', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products_photos')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Unit')),
            ],
        ),
    ]
