# Generated by Django 3.0.5 on 2020-05-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(default='ALIMENTÍCIOS', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(default='UNIDADE', max_length=20),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
